### PR TITLE
Support 1.20.4

### LINKED ISSUE #42: 1.20.3/4 support
Another protocol change, urgh.

### PR DESCRIPTION
**Pull request by NoaHimesaka1873**
Closes #42

### CODE REVIEW

**Comment by NoaHimesaka1873** [comment]
Hmm... I successfully built it on Arch Linux w/ JetBrains IntelliJ + OpenJDK 17 and running it with Purpur w/ Oracle GraalVM (Java 17)

**Comment by NoaHimesaka1873** [comment]
> Hmm... I successfully built it on Arch Linux w/ JetBrains IntelliJ + OpenJDK 17 and running it with Purpur w/ Oracle GraalVM (Java 17)
> Also, you're using the wrong file. You should use one without -dev suffix.

CC: @Potothingi

**Comment by AIMBOT312** [comment]
Where can we download this version built for 1.20.4?

**Comment by pop4959** [comment]
This looks good to me. Also tested and appears to work just fine. Thanks!

**Comment by NoaHimesaka1873** [comment]
> Where can we download this version built for 1.20.4?

Build it yourself, it's not that hard.

**Review by Kichura — APPROVED** [review]
LGTM.

**Comment by Askarionn** [comment]
Hello! I tried to build it myself, but I get this error:
https://pastebin.com/M6k8M3fL
Using Gradle -> build -> jar

**Pull request merged**
